name: Hello world workflow

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  hello-world:
    runs-on: [Self-hosted,Windows,X64]
    
    steps:
      - name: Print message
        run: |
          echo "Hello world"
          Start-Sleep -Seconds 20
          echo "Bye"
        

      
    
